version: '3.2'

services:
    frontend:
        depends_on:
            - backend
        build: frontend
        volumes:
            - ./frontend:/app
            - node_modules:/app/node_modules
        ports:
            - "80:3000"
        environment:
            - NODE_ENV=development
            - REACT_APP_BASE_URL=${FE_BASE_URL}
        command: npm run dev
    backend:
        depends_on:
            - db
        build: backend
        environment:
            - DEBUG=${BE_DEBUG}
            - SECRET_KEY=${BE_SECRET_KEY}
            - DB_HOST=${DB_HOST}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_PORT=${DB_PORT}
        volumes:
            - ./backend:/app/backend
        ports:
            - "8000:8000"
              #command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn --bind 0.0.0.0:8000 webshop.wsgi"
              #command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        stdin_open: true
        tty: true
        command: python manage.py runserver 0.0.0.0:8000
              #bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
              #command: /usr/local/bin/gunicorn budget.wsgi -w 2 -b :8000 --reload
              #command: gunicorn budget.wsgi 

    db:
        image: postgres
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - budget:/var/lib/postgresql/data

volumes:
    budget:
    node_modules:


